@startuml

[*] --> DisplaySplashScreen : AppLaunched

DisplaySplashScreen --> DisplayMainScreen : LoadingFinishedAndUserLoggedIn
DisplaySplashScreen --> DisplayLoginScreen : LoadingFinishedAndUserNotLoggedIn

DisplayMainScreen --> [*] : AppClosed
DisplayLoginScreen --> [*] : AppClosed

@enduml